name: py
channels:
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==2.0.0
    - anyio==4.3.0
    - astor==0.8.1
    - certifi==2023.11.17
    - charset-normalizer==3.3.2
    - coloredlogs==15.0.1
    - contextlib2==21.6.0
    - contourpy==1.1.1
    - cycler==0.12.1
    - decorator==5.1.1
    - exceptiongroup==1.2.1
    - filelock==3.13.1
    - flatbuffers==24.3.25
    - fonttools==4.47.0
    - fsspec==2023.12.2
    - ftfy==6.2.0
    - grad-cam==1.5.0
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.20.2
    - humanfriendly==10.0
    - idna==3.6
    - importlib-resources==6.1.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - markupsafe==2.1.3
    - matplotlib==3.7.4
    - ml-collections==0.1.1
    - mpmath==1.3.0
    - numpy==1.24.4
    - onnxruntime==1.17.3
    - opencv-python==4.9.0.80
    - opt-einsum==3.3.0
    - packaging==23.2
    - paddle-bfloat==0.1.7
    - paddle2onnx==1.2.1
    - paddlepaddle==2.5.0
    - pillow==10.2.0
    - protobuf==5.26.1
    - psutil==5.9.7
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pyyaml==6.0.1
    - regex==2024.4.28
    - requests==2.31.0
    - safetensors==0.4.1
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - six==1.16.0
    - sniffio==1.3.1
    - sympy==1.12
    - threadpoolctl==3.2.0
    - timm==0.9.12
    - torch==1.12.1+cu113
    - torch-cluster==1.6.0+pt112cu113
    - torch-geometric==2.4.0
    - torch-scatter==2.1.0+pt112cu113
    - torch-sparse==0.6.15+pt112cu113
    - torch-spline-conv==1.2.1+pt112cu113
    - torchaudio==0.12.1+cu113
    - torchvision==0.13.1+cu113
    - tqdm==4.66.1
    - ttach==0.0.3
    - typing-extensions==4.9.0
    - urllib3==2.1.0
    - wcwidth==0.2.13
    - yacs==0.1.8
    - zipp==3.17.0
prefix: /home/wr/anaconda3/envs/py
